[package]
name = "kfs-1"
version = "0.1.0"
edition = "2021"
[lib]
crate-type = ["staticlib"]
[profile.dev]
panic = "abort"
[profile.release]
panic = "abort"

[dependencies]
rlibc = "1.0.0"
spin = "0.9.8"
[dependencies.lazy_static]
version = "1.5.0"
features = ["spin_no_std"]